export const strings = {
    participantRegistrationForm: "Participant registration form",
    customiseForm: 'Customise form',
    preview: 'Preview',
    viewResponses: 'View responses',
    startWritingDescriptionAboutYoutForm: "Start writing description about your form...",
    selectYourSkills: 'Select your skills',
    selectTheLanguagesYouSpeak: 'Select the languages you speak',
    newQuestion: '+ New question',
    questionType: 'Question type',
    searchForAQuestionType: 'Search for a question type',
    type: 'Type',
    text: 'Text',
    number: 'Number',
    multipleChoice: 'Multiple choice',
    date: 'Date',
    person: 'Person',
    filesAndMedia: 'Files & media',
    checkbox: 'Checkbox',
    link: 'Link',
    email: 'Email',
    mobileNumber: 'MobileNumber',
    addAQuestion: 'Add a question',
    addQuestionDescription: 'Add question description',
    respondant: '(Respondant can select as many as they like)',
    option: 'Option',
    addOption: 'Add option',
    questionOptions: 'Question options',
    required: 'Required',
    description: 'Description',
    maxSelection: 'Max selection',
    viewLinkedAttribute: 'View linked attribute',
    syncWithAttributeName: 'Sync with attribute name',
    duplicateQuestion: 'Duplicate question',
    deleteQuestion: 'Delete question',
}